/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Baralho.*;
import Controller.ControllerRodada;
import java.awt.Dimension;
import java.awt.Image;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author rafael
 */
public class Truco extends javax.swing.JFrame {

    /**
     * Creates new form Truco
     */
    private ControllerRodada controlRodada;
    private static Baralho baralho;

    static {

        Monte principal = new MonteComum();
        MonteDescarte descarte = new MonteDescarte();

        List<Integer> sequencia = new ArrayList<Integer>();

        for (int i = 1; i <= 13; i++) {
            switch (i) {
                case 8:
                    continue;
                case 9:
                    continue;
                case 10:
                    continue;
            }

            sequencia.add(i);
        }

        baralho = new Baralho(principal, descarte, new ComparacaoSimples(), sequencia);
    }

    public Truco() {

        initComponents();
        baralho.embaralhar();
        baralho.embaralhar();
        baralho.embaralhar();
        ajustarTamanhos();
        ajustarCartas();
        this.setSize(560, 530);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    private void ajustarTamanhos() {

        pCartaAdv1.setSize(84, 113);
        pCartaAdv2.setSize(84, 113);
        pCartaAdv3.setSize(84, 113);
        pCartaMao1.setSize(84, 113);
        pCartaMao2.setSize(84, 113);
        pCartaMao3.setSize(84, 113);
        pCartaVira.setSize(47, 67);
        //pCartaMesa1.setPreferredSize(new Dimension(68,90));
        pCartaMesa1.setSize(68, 90);
        pCartaMesa2.setSize(68, 90);
        pMontePrincipal.setSize(47, 67);
        pMonteDescarte.setSize(47, 67);
    }

    private void ajustarCartas() {

        ajustarImagem(pCartaAdv1, lbCartaAdv1, new ImageIcon("img cartas/155.gif"));
        ajustarImagem(pCartaAdv2, lbCartaAdv2, new ImageIcon("img cartas/155.gif"));
        ajustarImagem(pCartaAdv3, lbCartaAdv3, new ImageIcon("img cartas/155.gif"));
        ajustarImagem(pCartaMao1, lbCartaMao1, baralho.retirarCartaDoFim().getImgCarta());
        ajustarImagem(pCartaMao2, lbCartaMao2, baralho.retirarCartaDoFim().getImgCarta());
        ajustarImagem(pCartaMao3, lbCartaMao3, baralho.retirarCartaDoFim().getImgCarta());
        ajustarImagem(pCartaVira, lbCartaVira, baralho.retirarCartaDoInicio().getImgCarta());
        //ajustarImagem(pCartaMesa1, lbCartaMesa1, new ImageIcon("img cartas/130.gif"));
        //ajustarImagem(pCartaMesa2, lbCartaMesa2, new ImageIcon("img cartas/132.gif"));
        ajustarImagem(pMontePrincipal, lbMontePrincipal, new ImageIcon("img cartas/155.gif"));
        ajustarImagem(pMonteDescarte, lbMonteDescarte, new ImageIcon("img cartas/155.gif"));
    }

    private void ajustarImagem(JPanel pImagem, JLabel lbImagem, ImageIcon imagem) {

        lbImagem.setIcon(new ImageIcon(imagem.getImage().getScaledInstance(pImagem.getWidth(), pImagem.getHeight(), Image.SCALE_DEFAULT)));
    }

    public boolean jogaCartaNaMesa(ImageIcon imgCarta) {

        if (lbCartaMesa1.getIcon() == null) {

            this.ajustarImagem(pCartaMesa1, lbCartaMesa1, imgCarta);
            return true;
        } else if (lbCartaMesa2.getIcon() == null) {

            this.ajustarImagem(pCartaMesa2, lbCartaMesa2, imgCarta);
            return true;
        }

        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelInfo = new javax.swing.JPanel();
        pMontes = new javax.swing.JPanel();
        pMontePrincipal = new javax.swing.JPanel();
        lbMontePrincipal = new javax.swing.JLabel();
        pMonteDescarte = new javax.swing.JPanel();
        lbMonteDescarte = new javax.swing.JLabel();
        pInfoJogs = new javax.swing.JPanel();
        lbJog1 = new javax.swing.JLabel();
        lbJog2 = new javax.swing.JLabel();
        lbPontosJog1 = new javax.swing.JLabel();
        lbPontosJog2 = new javax.swing.JLabel();
        pTruco = new javax.swing.JPanel();
        btTruco = new javax.swing.JButton();
        pPontuação = new javax.swing.JPanel();
        lbPontuação = new javax.swing.JLabel();
        lbValPontuação = new javax.swing.JLabel();
        pBotões = new javax.swing.JPanel();
        btNovo = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        panelCartas = new javax.swing.JPanel();
        pCartaAdv1 = new javax.swing.JPanel();
        lbCartaAdv1 = new javax.swing.JLabel();
        pCartaAdv2 = new javax.swing.JPanel();
        lbCartaAdv2 = new javax.swing.JLabel();
        pCartaAdv3 = new javax.swing.JPanel();
        lbCartaAdv3 = new javax.swing.JLabel();
        pCartaMesa1 = new javax.swing.JPanel();
        lbCartaMesa1 = new javax.swing.JLabel();
        pCartaVira = new javax.swing.JPanel();
        lbCartaVira = new javax.swing.JLabel();
        pCartaMesa2 = new javax.swing.JPanel();
        lbCartaMesa2 = new javax.swing.JLabel();
        pCartaMao1 = new javax.swing.JPanel();
        lbCartaMao1 = new javax.swing.JLabel();
        pCartaMao2 = new javax.swing.JPanel();
        lbCartaMao2 = new javax.swing.JLabel();
        pCartaMao3 = new javax.swing.JPanel();
        lbCartaMao3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Truco Simples");

        panelInfo.setLayout(new javax.swing.BoxLayout(panelInfo, javax.swing.BoxLayout.Y_AXIS));

        pMontes.setBorder(javax.swing.BorderFactory.createTitledBorder("Montes"));
        pMontes.setPreferredSize(new java.awt.Dimension(124, 200));
        pMontes.setLayout(new java.awt.GridBagLayout());

        pMontePrincipal.setBackground(new java.awt.Color(51, 51, 51));
        pMontePrincipal.setLayout(new java.awt.BorderLayout());
        pMontePrincipal.add(lbMontePrincipal, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        pMontes.add(pMontePrincipal, gridBagConstraints);

        pMonteDescarte.setBackground(new java.awt.Color(51, 51, 51));
        pMonteDescarte.setLayout(new java.awt.BorderLayout());
        pMonteDescarte.add(lbMonteDescarte, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        pMontes.add(pMonteDescarte, gridBagConstraints);

        panelInfo.add(pMontes);

        pInfoJogs.setBorder(javax.swing.BorderFactory.createTitledBorder("Jogadores"));
        pInfoJogs.setPreferredSize(new java.awt.Dimension(124, 69));
        pInfoJogs.setLayout(new java.awt.GridBagLayout());

        lbJog1.setText("Jogador 1:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        pInfoJogs.add(lbJog1, gridBagConstraints);

        lbJog2.setText("Jogador 2:");
        lbJog2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbJog2MouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        pInfoJogs.add(lbJog2, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        pInfoJogs.add(lbPontosJog1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        pInfoJogs.add(lbPontosJog2, gridBagConstraints);

        panelInfo.add(pInfoJogs);

        pTruco.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pTruco.setPreferredSize(new java.awt.Dimension(124, 69));
        pTruco.setLayout(new java.awt.GridBagLayout());

        btTruco.setText("Truco");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        pTruco.add(btTruco, gridBagConstraints);

        panelInfo.add(pTruco);

        pPontuação.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pPontuação.setPreferredSize(new java.awt.Dimension(124, 69));
        pPontuação.setLayout(new java.awt.GridBagLayout());

        lbPontuação.setText("Pontuação");
        pPontuação.add(lbPontuação, new java.awt.GridBagConstraints());
        pPontuação.add(lbValPontuação, new java.awt.GridBagConstraints());

        panelInfo.add(pPontuação);

        pBotões.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pBotões.setPreferredSize(new java.awt.Dimension(124, 69));
        pBotões.setLayout(new java.awt.GridBagLayout());

        btNovo.setText("Novo Jogo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        pBotões.add(btNovo, gridBagConstraints);

        btSair.setText("Sair");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        pBotões.add(btSair, gridBagConstraints);

        panelInfo.add(pBotões);

        getContentPane().add(panelInfo, java.awt.BorderLayout.LINE_END);

        panelCartas.setLayout(new java.awt.GridBagLayout());

        pCartaAdv1.setMinimumSize(new java.awt.Dimension(84, 113));
        pCartaAdv1.setLayout(new java.awt.BorderLayout());
        pCartaAdv1.add(lbCartaAdv1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelCartas.add(pCartaAdv1, gridBagConstraints);

        pCartaAdv2.setBackground(new java.awt.Color(255, 0, 51));
        pCartaAdv2.setLayout(new java.awt.BorderLayout());
        pCartaAdv2.add(lbCartaAdv2, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelCartas.add(pCartaAdv2, gridBagConstraints);

        pCartaAdv3.setBackground(new java.awt.Color(255, 0, 0));
        pCartaAdv3.setLayout(new java.awt.BorderLayout());
        pCartaAdv3.add(lbCartaAdv3, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelCartas.add(pCartaAdv3, gridBagConstraints);

        pCartaMesa1.setBackground(new java.awt.Color(0, 0, 255));
        pCartaMesa1.setPreferredSize(new java.awt.Dimension(68, 90));
        pCartaMesa1.setLayout(new java.awt.BorderLayout());
        pCartaMesa1.add(lbCartaMesa1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        panelCartas.add(pCartaMesa1, gridBagConstraints);

        pCartaVira.setBackground(new java.awt.Color(51, 51, 51));
        pCartaVira.setLayout(new java.awt.BorderLayout());
        pCartaVira.add(lbCartaVira, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        panelCartas.add(pCartaVira, gridBagConstraints);

        pCartaMesa2.setBackground(new java.awt.Color(51, 51, 255));
        pCartaMesa2.setPreferredSize(new java.awt.Dimension(68, 90));
        pCartaMesa2.setLayout(new java.awt.BorderLayout());
        pCartaMesa2.add(lbCartaMesa2, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 20);
        panelCartas.add(pCartaMesa2, gridBagConstraints);

        pCartaMao1.setBackground(new java.awt.Color(255, 255, 255));
        pCartaMao1.setLayout(new java.awt.BorderLayout());

        lbCartaMao1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCartaMao1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lbCartaMao1MouseReleased(evt);
            }
        });
        pCartaMao1.add(lbCartaMao1, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelCartas.add(pCartaMao1, gridBagConstraints);

        pCartaMao2.setBackground(new java.awt.Color(255, 255, 255));
        pCartaMao2.setLayout(new java.awt.BorderLayout());

        lbCartaMao2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCartaMao2MouseClicked(evt);
            }
        });
        pCartaMao2.add(lbCartaMao2, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelCartas.add(pCartaMao2, gridBagConstraints);

        pCartaMao3.setBackground(new java.awt.Color(255, 255, 255));
        pCartaMao3.setLayout(new java.awt.BorderLayout());

        lbCartaMao3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbCartaMao3MouseClicked(evt);
            }
        });
        pCartaMao3.add(lbCartaMao3, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelCartas.add(pCartaMao3, gridBagConstraints);

        getContentPane().add(panelCartas, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbCartaMao1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCartaMao1MouseReleased
    }//GEN-LAST:event_lbCartaMao1MouseReleased

    private void lbJog2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbJog2MouseClicked
    }//GEN-LAST:event_lbJog2MouseClicked

    private void lbCartaMao1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCartaMao1MouseClicked

        this.controlRodada.jogaCarta((JLabel) evt.getSource());
    }//GEN-LAST:event_lbCartaMao1MouseClicked

    private void lbCartaMao2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCartaMao2MouseClicked

        this.controlRodada.jogaCarta((JLabel) evt.getSource());
    }//GEN-LAST:event_lbCartaMao2MouseClicked

    private void lbCartaMao3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbCartaMao3MouseClicked

        this.controlRodada.jogaCarta((JLabel) evt.getSource());
    }//GEN-LAST:event_lbCartaMao3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Truco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Truco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Truco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Truco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Truco().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNovo;
    private javax.swing.JButton btSair;
    private javax.swing.JButton btTruco;
    private javax.swing.JLabel lbCartaAdv1;
    private javax.swing.JLabel lbCartaAdv2;
    private javax.swing.JLabel lbCartaAdv3;
    private javax.swing.JLabel lbCartaMao1;
    private javax.swing.JLabel lbCartaMao2;
    private javax.swing.JLabel lbCartaMao3;
    private javax.swing.JLabel lbCartaMesa1;
    private javax.swing.JLabel lbCartaMesa2;
    private javax.swing.JLabel lbCartaVira;
    private javax.swing.JLabel lbJog1;
    private javax.swing.JLabel lbJog2;
    private javax.swing.JLabel lbMonteDescarte;
    private javax.swing.JLabel lbMontePrincipal;
    private javax.swing.JLabel lbPontosJog1;
    private javax.swing.JLabel lbPontosJog2;
    private javax.swing.JLabel lbPontuação;
    private javax.swing.JLabel lbValPontuação;
    private javax.swing.JPanel pBotões;
    private javax.swing.JPanel pCartaAdv1;
    private javax.swing.JPanel pCartaAdv2;
    private javax.swing.JPanel pCartaAdv3;
    private javax.swing.JPanel pCartaMao1;
    private javax.swing.JPanel pCartaMao2;
    private javax.swing.JPanel pCartaMao3;
    private javax.swing.JPanel pCartaMesa1;
    private javax.swing.JPanel pCartaMesa2;
    private javax.swing.JPanel pCartaVira;
    private javax.swing.JPanel pInfoJogs;
    private javax.swing.JPanel pMonteDescarte;
    private javax.swing.JPanel pMontePrincipal;
    private javax.swing.JPanel pMontes;
    private javax.swing.JPanel pPontuação;
    private javax.swing.JPanel pTruco;
    private javax.swing.JPanel panelCartas;
    private javax.swing.JPanel panelInfo;
    // End of variables declaration//GEN-END:variables

    public ControllerRodada getControlRodada() {

        return controlRodada;
    }

    public void setControlRodada(ControllerRodada controlRodada) {

        this.controlRodada = controlRodada;
    }

    public JLabel getLbCartaAdv1() {
        return lbCartaAdv1;
    }

    public void setLbCartaAdv1(JLabel lbCartaAdv1) {
        this.lbCartaAdv1 = lbCartaAdv1;
    }

    public JLabel getLbCartaAdv2() {
        return lbCartaAdv2;
    }

    public void setLbCartaAdv2(JLabel lbCartaAdv2) {
        this.lbCartaAdv2 = lbCartaAdv2;
    }

    public JLabel getLbCartaAdv3() {
        return lbCartaAdv3;
    }

    public void setLbCartaAdv3(JLabel lbCartaAdv3) {
        this.lbCartaAdv3 = lbCartaAdv3;
    }

    public JLabel getLbCartaMao1() {
        return lbCartaMao1;
    }

    public void setLbCartaMao1(JLabel lbCartaMao1) {
        this.lbCartaMao1 = lbCartaMao1;
    }

    public JLabel getLbCartaMao2() {
        return lbCartaMao2;
    }

    public void setLbCartaMao2(JLabel lbCartaMao2) {
        this.lbCartaMao2 = lbCartaMao2;
    }

    public JLabel getLbCartaMao3() {
        return lbCartaMao3;
    }

    public void setLbCartaMao3(JLabel lbCartaMao3) {
        this.lbCartaMao3 = lbCartaMao3;
    }

    public JLabel getLbCartaMesa1() {
        return lbCartaMesa1;
    }

    public void setLbCartaMesa1(JLabel lbCartaMesa1) {
        this.lbCartaMesa1 = lbCartaMesa1;
    }

    public JLabel getLbCartaMesa2() {
        return lbCartaMesa2;
    }

    public void setLbCartaMesa2(JLabel lbCartaMesa2) {
        this.lbCartaMesa2 = lbCartaMesa2;
    }

    public JLabel getLbCartaVira() {
        return lbCartaVira;
    }

    public void setLbCartaVira(JLabel lbCartaVira) {
        this.lbCartaVira = lbCartaVira;
    }

    public JLabel getLbMonteDescarte() {
        return lbMonteDescarte;
    }

    public void setLbMonteDescarte(JLabel lbMonteDescarte) {
        this.lbMonteDescarte = lbMonteDescarte;
    }

    public JLabel getLbMontePrincipal() {
        return lbMontePrincipal;
    }

    public void setLbMontePrincipal(JLabel lbMontePrincipal) {
        this.lbMontePrincipal = lbMontePrincipal;
    }

    public JLabel getLbPontosJog1() {
        return lbPontosJog1;
    }

    public void setLbPontosJog1(JLabel lbPontosJog1) {
        this.lbPontosJog1 = lbPontosJog1;
    }

    public JLabel getLbPontosJog2() {
        return lbPontosJog2;
    }

    public void setLbPontosJog2(JLabel lbPontosJog2) {
        this.lbPontosJog2 = lbPontosJog2;
    }

    public JLabel getLbPontuação() {
        return lbPontuação;
    }

    public void setLbPontuação(JLabel lbPontuação) {
        this.lbPontuação = lbPontuação;
    }

    public JPanel getpCartaAdv1() {
        return pCartaAdv1;
    }

    public void setpCartaAdv1(JPanel pCartaAdv1) {
        this.pCartaAdv1 = pCartaAdv1;
    }

    public JPanel getpCartaAdv2() {
        return pCartaAdv2;
    }

    public void setpCartaAdv2(JPanel pCartaAdv2) {
        this.pCartaAdv2 = pCartaAdv2;
    }

    public JPanel getpCartaAdv3() {
        return pCartaAdv3;
    }

    public void setpCartaAdv3(JPanel pCartaAdv3) {
        this.pCartaAdv3 = pCartaAdv3;
    }

    public JPanel getpCartaMao1() {
        return pCartaMao1;
    }

    public void setpCartaMao1(JPanel pCartaMao1) {
        this.pCartaMao1 = pCartaMao1;
    }

    public JPanel getpCartaMao2() {
        return pCartaMao2;
    }

    public void setpCartaMao2(JPanel pCartaMao2) {
        this.pCartaMao2 = pCartaMao2;
    }

    public JPanel getpCartaMao3() {
        return pCartaMao3;
    }

    public void setpCartaMao3(JPanel pCartaMao3) {
        this.pCartaMao3 = pCartaMao3;
    }

    public JPanel getpCartaMesa1() {
        return pCartaMesa1;
    }

    public void setpCartaMesa1(JPanel pCartaMesa1) {
        this.pCartaMesa1 = pCartaMesa1;
    }

    public JPanel getpCartaMesa2() {
        return pCartaMesa2;
    }

    public void setpCartaMesa2(JPanel pCartaMesa2) {
        this.pCartaMesa2 = pCartaMesa2;
    }

    public JPanel getpCartaVira() {
        return pCartaVira;
    }

    public void setpCartaVira(JPanel pCartaVira) {
        this.pCartaVira = pCartaVira;
    }
}
